--------------------------------------------------------
--  File created - Thursday-November-12-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LINEITEM
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."LINEITEM" 
   (	"PURCHASENO" NUMBER(*,0), 
	"PRODUCTNAME" VARCHAR2(100 BYTE), 
	"PRICE" FLOAT(126), 
	"IMAGE" VARCHAR2(50 BYTE), 
	"PRODUCTCOST" FLOAT(126), 
	"QUANTITY" NUMBER(*,0), 
	"PURCHASEDATE" DATE, 
	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTREVIEW
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."PRODUCTREVIEW" 
   (	"REVIEWID" NUMBER(*,0), 
	"PRODUCTID" NUMBER(*,0), 
	"POST" VARCHAR2(200 BYTE), 
	"POSTSTAR" NUMBER(*,0), 
	"POSTDATE" DATE, 
	"USERNAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."PRODUCTS" 
   (	"PRODID" NUMBER(*,0), 
	"PRODNAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE), 
	"PRICE" FLOAT(126), 
	"IMAGE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SHOPPINGUSER
--------------------------------------------------------

  CREATE TABLE "TESTUSERDB"."SHOPPINGUSER" 
   (	"USERID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"USERPWD" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTUSERDB.LINEITEM
SET DEFINE OFF;
Insert into TESTUSERDB.LINEITEM (PURCHASENO,PRODUCTNAME,PRICE,IMAGE,PRODUCTCOST,QUANTITY,PURCHASEDATE,USERID,USERNAME) values (32,'The Lost Codex',14.21,'image1.jpg',14.21,1,to_date('12-NOV-15','DD-MON-RR'),26,'114');
Insert into TESTUSERDB.LINEITEM (PURCHASENO,PRODUCTNAME,PRICE,IMAGE,PRODUCTCOST,QUANTITY,PURCHASEDATE,USERID,USERNAME) values (36,'The Lost Codex',14.21,'image1.jpg',56.84,4,to_date('12-NOV-15','DD-MON-RR'),23,'336');
Insert into TESTUSERDB.LINEITEM (PURCHASENO,PRODUCTNAME,PRICE,IMAGE,PRODUCTCOST,QUANTITY,PURCHASEDATE,USERID,USERNAME) values (35,'The Lost Codex',14.21,'image1.jpg',14.21,1,to_date('12-NOV-15','DD-MON-RR'),23,'336');
REM INSERTING into TESTUSERDB.PRODUCTREVIEW
SET DEFINE OFF;
Insert into TESTUSERDB.PRODUCTREVIEW (REVIEWID,PRODUCTID,POST,POSTSTAR,POSTDATE,USERNAME) values (1,2,'Good Product',1,to_date('12-NOV-15','DD-MON-RR'),'336');
Insert into TESTUSERDB.PRODUCTREVIEW (REVIEWID,PRODUCTID,POST,POSTSTAR,POSTDATE,USERNAME) values (2,2,'Another good review here!! I just like it..',5,to_date('12-NOV-15','DD-MON-RR'),'335');
Insert into TESTUSERDB.PRODUCTREVIEW (REVIEWID,PRODUCTID,POST,POSTSTAR,POSTDATE,USERNAME) values (3,1,'A nice book',4,to_date('12-NOV-15','DD-MON-RR'),'336');
Insert into TESTUSERDB.PRODUCTREVIEW (REVIEWID,PRODUCTID,POST,POSTSTAR,POSTDATE,USERNAME) values (4,1,'A nice book',4,to_date('12-NOV-15','DD-MON-RR'),'336');
Insert into TESTUSERDB.PRODUCTREVIEW (REVIEWID,PRODUCTID,POST,POSTSTAR,POSTDATE,USERNAME) values (5,1,'Just a review',5,to_date('12-NOV-15','DD-MON-RR'),'336');
REM INSERTING into TESTUSERDB.PRODUCTS
SET DEFINE OFF;
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (1,'The Lost Codex','A masterwork of international suspense and an outstanding novel',14.21,'image1.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (2,'Do Unto Animals','A gift for animal lovers of all stripes',16.76,'image2.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (3,'Mother Gooses Pajama Party','Star light, star bright, come to story time tonight',13.35,'image3.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (4,'Nana in the City','The succinct text is paired with watercolor illustrations that capture all the vitality, energy, and beauty of the city',10.18,'image4.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (5,'2001: a Space Odyssey','Inspired what is perhaps the greatest science fiction film ever made',21.69,'image5.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (6,'A Canticle for Leibowitz','One of the most accomplished, powerful, and enduring classics of modern speculative fiction',10.96,'image6.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (7,'A Game of Thrones','One of those rare reading experiences that catch you up from the opening pages, won’t let you go until the end, and leave you yearning for more',11.25,'image7.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (8,'A Wrinkle in Time','A Wrinkle in Time is the winner of the 1963 Newbery Medal',5.89,'image8.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (9,'Altered Carbon','Takeshi Kovacs Novels',10.26,'image9.jpg');
Insert into TESTUSERDB.PRODUCTS (PRODID,PRODNAME,DESCRIPTION,PRICE,IMAGE) values (10,'American Gods','American Gods is Neil Gaiman best and most ambitious novel yet, a scary, strange, and hallucinogenic road-trip story wrapped around a deep examination of the American spirit',18.89,'image10.jpg');
REM INSERTING into TESTUSERDB.SHOPPINGUSER
SET DEFINE OFF;
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (4,'234','234','234@nyu.edu');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (5,'333','333','333@nyu.edu');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (6,'444','444','444@444.com');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (7,'555','555',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (8,'666','666',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (9,null,null,null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (10,null,null,null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (11,'33','33',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (12,'777','777',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (13,'888','888',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (14,'999','999',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (15,'00','00',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (16,'01','01',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (17,'001','001',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (18,'010','010',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (19,'111','111',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (20,'112','112',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (2,'123','123','123@123.com');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (3,'12','12','12@nyu.edu');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (24,'337','337',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (22,'335','335',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (23,'336','336',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (25,'102','102',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (26,'114','114',null);
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (1,'lily','123','lily@123.com');
Insert into TESTUSERDB.SHOPPINGUSER (USERID,USERNAME,USERPWD,EMAIL) values (21,'admin','admin',null);
--------------------------------------------------------
--  DDL for Index SYS_C007701
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007701" ON "TESTUSERDB"."LINEITEM" ("PURCHASENO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007702
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007702" ON "TESTUSERDB"."PRODUCTREVIEW" ("REVIEWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007602
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007602" ON "TESTUSERDB"."PRODUCTS" ("PRODID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007674
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTUSERDB"."SYS_C007674" ON "TESTUSERDB"."SHOPPINGUSER" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LINEITEM
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."LINEITEM" ADD PRIMARY KEY ("PURCHASENO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTREVIEW
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."PRODUCTREVIEW" ADD PRIMARY KEY ("REVIEWID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."PRODUCTS" ADD PRIMARY KEY ("PRODID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SHOPPINGUSER
--------------------------------------------------------

  ALTER TABLE "TESTUSERDB"."SHOPPINGUSER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
